name: Build PhoneBack

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and Archive
        run: |
          xcodebuild -project PhoneBack.xcodeproj -scheme PhoneBackApp -configuration Release -archivePath ./build/PhoneBack.xcarchive archive
          xcodebuild -exportArchive -archivePath ./build/PhoneBack.xcarchive -exportOptionsPlist ./ExportOptions.plist -exportPath ./build

      - name: Upload PhoneBack.app
        uses: actions/upload-artifact@v4
        with:
          name: PhoneBack-App
          path: ./build/PhoneBack.app
